version: '3.5'
services:
    nginx:
        build: .
        image: avzd/nginx-le:latest
        container_name: nginx-le

        restart: always

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        ports:
            - "80:80"
            - "443:443"

        environment:
            ## Space-separated list of domains to host
            SERVER_NAMES: api.example.com api2.example.com

            ## https://letsencrypt.org/docs/expiration-emails/
            LE_EMAIL: bob@example.com

            ## Simple proxy HTTP
            # PROXY_PASS: http://host:8080

            ## OR

            ## FastCGI (e.g. for php-fpm):
            # FASTCGI_PASS: http://host:9000
            # FASTCGI_PARAM_SCRIPT_FILENAME=/sources/index.php

            ## ...
            ## See all options in Dockerfile ENV

        # volumes:
            ## To make dhparams persistent
            # - /path/to/ssl:/etc/nginx/ssl

            ## To make certificates persistent
            # - /path/to/letsencrypt:/etc/letsencrypt
